# Generated by Django 4.1.6 on 2023-02-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencys',
            name='name',
        ),
        migrations.RemoveField(
            model_name='agencys',
            name='owner',
        ),
    ]
