# Generated by Django 4.1.6 on 2023-02-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0003_alter_packages_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencys',
            name='id',
        ),
        migrations.AlterField(
            model_name='agencys',
            name='location',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
