# Generated by Django 4.1.6 on 2023-02-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0004_remove_agencys_id_alter_agencys_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencys',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencys',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
