# Generated by Django 4.1.6 on 2023-02-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0005_agencys_id_alter_agencys_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofiles',
            old_name='RegistrationDocument',
            new_name='Employementcertificate',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='AgencyName',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='Ownername',
        ),
    ]
