# Generated by Django 4.1.6 on 2023-02-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0007_alter_staffprofiles_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofiles',
            old_name='username',
            new_name='staff',
        ),
    ]
