# Generated by Django 4.1.6 on 2023-02-28 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myapplication', '0008_rename_username_staffprofiles_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofiles',
            old_name='Employementcertificate',
            new_name='Document',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='staff',
        ),
        migrations.AddField(
            model_name='staffprofiles',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofiles',
            name='username1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
