# Generated by Django 4.1.6 on 2023-03-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
