# Generated by Django 4.1.6 on 2023-03-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0012_userprofiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofiles',
            old_name='AddressLine1',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='staffprofiles',
            old_name='AddressLine2',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='staffprofiles',
            old_name='Area',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='status',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='Document',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='Mobilenumber',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='Postcode',
        ),
        migrations.RemoveField(
            model_name='staffprofiles',
            name='State',
        ),
    ]
