# Generated by Django 4.1.6 on 2023-03-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0013_rename_addressline1_staffprofiles_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='status',
            field=models.CharField(choices=[('1', 'available')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
