# Generated by Django 4.1.6 on 2023-03-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0014_packages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_type',
            field=models.CharField(choices=[('1', 'Diamond'), ('2', 'Gold'), ('3', 'Silver')], max_length=50),
        ),
    ]
